version: '3.8'

services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: root_pass
    depends_on:
      - mysql
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - zabbix-network

  zabbix-web:
    build: .
    #image: zabbix/zabbix-web-nginx-mysql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    ports:
      - "8080:8080"
    depends_on:
      - zabbix-server
      - mysql
    networks:
      - zabbix-network


  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - zabbix-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_CACHE_TTL=30s
      - GF_DATAPROXY_CACHE_TTL=0s
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - zabbix-web
    networks:
      - zabbix-network

networks:
  zabbix-network:
    driver: bridge

volumes:
  zabbix_server_data:
  grafana_data:
  mysql_data:
